apiVersion: v1
kind: Secret
metadata:
  name: aws-secret # Name of the secret
  namespace: default # Namespace of the secret
type: opaque
data:
  accessKeyId: QUtJQVUyMkpITE1NMkg1STMzVk0=
  secretAccessKey: SWpzUEZ6eGVKc1FVeU1icXIwS2xncFYvM0dJendNWlhPN2JobkhpMw==